[build]
# The index html to drive the bundling process 
target = "index.html"
# The output dir for all final assets 
dist = "dist"


[clean]
# The out dir for all finalassets
dist = "dist"
# Optionally perform a cargo clean 
cargo = false


[serve]
# The address to serve on.
addr = "127.0.0.1"
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = false