version: '3.9'
services:
  accounts:
    build:
      context:  .
      dockerfile: ./accounts/Dockerfile
  products:
    build:
      context:  .
      dockerfile: ./products/Dockerfile
  reviews:
    build:
      context:  .
      dockerfile: ./reviews/Dockerfile
  inventory:
    build:
      context:  .
      dockerfile: ./inventory/Dockerfile
  apollo-gateway: 
    build:
      context: ./apollo-gateway
      dockerfile: Dockerfile